refactor: Clean up the Taskfiles
Review and clean up some parts of the various taskfiles, including

- Moving all workspace/options settings into the terraform:workspace
  task, and making that a dependency to simplify code;
- Fixing the names of some tasks;
- Adding a dedicated zizmor task for running all zizmor tasks;
- Improving some descriptions and summaries; and
- Adding TF_BACKEND support for the terraform:init task.

diff --git a/.task/terraform.yaml b/.task/terraform.yaml
--- a/.task/terraform.yaml
+++ b/.task/terraform.yaml
@@ -59,6 +59,7 @@ tasks:
 
       - {{ .workspaces | join "\n- " }}
     silent: true
+    run: once
     vars:
       workspace:
         sh: cat .terraform/environment 2>/dev/null || echo -n "{{ .default }}"
@@ -67,17 +68,18 @@ tasks:
           case '{{ .workspace }}' in
             {{ .workspaces | join "|" }}) ;;
             *)
-              echo >&2 'The workspace selected (`{{ .workspace }}`) is invalid. Workspaces must be one of:'
-              echo >&2 '  {{ .workspaces | join ", " }}.'
+              echo >&2 'The workspace selected ({{ .workspace }}) is invalid.'
+              echo >&2 'Terraform workspaces must be one of:'
+              echo >&2 '  - {{ .workspaces | join "\n  - " }}'
               echo >&2 'Please run `task {{ .TASK }}:{{ .default }}` to reset.'
               exit 1
               ;;
           esac
       - cmd: |-
-          echo -e "workspace: \e[1;37m{{ .workspace }}\e[0m"
+          echo -e 'Workspace "{{ .workspace }}" is active.'
           if [[ -f "variables/{{ .workspace }}.tfvars" ]]; then
             FILE=$(realpath --relative-to="{{ .ROOT_DIR }}" "variables/{{ .workspace }}.tfvars")
-            echo -e "options:\n  \e[1;37m-var-file=${FILE}\e[0m"
+            echo -e "Additional arguments provided:\n  -var-file=${FILE}"
           fi
 
   terraform:workspace:*:
@@ -118,14 +120,14 @@ tasks:
           case '{{ .target }}' in
             {{ .workspaces | join "|" }}) ;;
             *)
-              echo -e >&2 'The workspace selected (`\e[1;37m{{ .target }}\e[0m`) is invalid.'
+              echo -e >&2 'The workspace selected ({{ .target }}) is invalid.'
               echo >&2 'Terraform workspaces must be one of:'
               echo -e >&2 '  - {{ .workspaces | join "\n  - " }}'
               echo >&2 'Please run `task {{ trimSuffix ":*" .TASK }}:{{ .default }}` to reset.'
               exit 1
               ;;
           esac
-      - cmd: "echo -e 'workspace: \e[1;37m{{ .target }}\e[0m'"
+      - cmd: echo -e 'Terraform workspace {{ .target }} selected'
       # If we're switching workspaces, ensure that any Terraform execution plan is removed, as it will be invalid
       - cmd: rm -f terraform.tfplan
       # If .terraform exists, then we can assume that we can just select the workspace to change to it, otherwise we
@@ -148,50 +150,58 @@ tasks:
     summary: |-
       (Re)Initialise the Terraform for the configuration, which will fetch any required Terraform modules and providers.
     sources:
-      # Monitor only the terraform.tf file as these is where provider versions will be configured, so any
-      # re-initialisation will only be needed when these change, rather than just any Terraform file
+      # Monitor only the terraform.tf file as this is where provider versions will be (or at least should be)
+      # configured, so any re-initialisation will only be needed only when this file changes.
       - terraform.tf
     silent: true
     run: when_changed
     deps:
+      - task: terraform:workspace
       - task: terraform:switch
     vars:
       workspace:
         sh: cat .terraform/environment 2>/dev/null || echo -n "{{ .default }}"
       repository:
         sh: basename '{{ .ROOT_DIR }}'
+      arguments:
+        # Assume we do not require the backend to be initialised, as it should only be done within the CI/CD pipeline,
+        # and not during local development. This is to avoid accidentally working with the state file in development.
+        sh: "[[ ${TF_BACKEND:-false} == 'false' ]] && echo -n ' -backend=false' || true"
     env:
       TF_IN_AUTOMATION: "true"
+      TF_INPUT: "false"
     cmds:
       - defer: "{{ if .EXIT_CODE }}echo -e '\e[1;31mFailed\e[0m'{{ end }}"
+      - defer: echo -n '{{ default "0" .EXIT_CODE }}' > '.terraform/init'
+      # Ensure the .terraform directory exists as tee will fail if it cannot create the init.log file
+      - cmd: mkdir -p .terraform
       # Perform a sanity check on the backend prefix to ensure this maps to the name of the repository, otherwise we may
       # accidentally overwrite another configuration's state files. Although the files are versioned, there remains a
-      # risk of accidental destruction of infrastructure if the wrong state file is used.
+      # risk of accidental destruction of infrastructure if the wrong state file is used. Additionally, ensure this is
+      # passed through to the init.log file so that it can be captured in the CI/CD pipeline logs for auditing purposes.
       - cmd: |-
           TFSTATE_FILE=$(hcledit attribute get terraform.backend.gcs.prefix -f terraform.tf 2>/dev/null | tr -d \")
           if [[ "${TFSTATE_FILE}" == "github/n3tuk/{{ .repository }}" ]]; then
             echo 'Validated the backend prefix for GCS.'
           else
-            echo -e '\e[1;31mThe prefix for the Terraform state file object path in the GCS backend\e[0m'
-            echo -e '\e[1;31mdoes not match the name of the repository.\e[0m Update the prefix used in the'
-            echo -e '\e[1;37mterraform/terraform.tf\e[0m file to the following prefix \e[1;37mbefore\e[0m continuing:'
-            echo
-            echo -e '      found: \e[1;31m'${TFSTATE_FILE}'\e[0m'
-            echo -e '   expected: github/n3tuk/\e[1;37m{{ .repository }}\e[0m'
+            (
+              echo 'The prefix for the Terraform state file object path in the GCS backend does not match the name'
+              echo 'of the repository. Update the prefix used in the terraform/terraform.tf file to the following'
+              echo 'prefix before continuing:'
+              echo
+              echo '      found: '${TFSTATE_FILE}
+              echo '   expected: github/n3tuk/{{ .repository }}'
+            ) |& tee .terraform/init.log
             echo
             exit 1
           fi
-      - cmd: "echo -e 'workspace: \e[1;37m{{ .workspace }}\e[0m'"
-      # If we're re-initilising, ensure that any Terraform execution plan is removed, as it may be invalid
+      # If we're re-initialising ensure that any Terraform execution plan is removed as it may be invalid
       - cmd: rm -f terraform.tfplan
-      # Ensure the .terraform directory exists as tee will fail if it cannot create the init.log file
-      - cmd: mkdir -p .terraform
-      - cmd: "{{ .ROOT_DIR }}/.bin/terraform init -upgrade -no-color -input=false |& tee '.terraform/init.log'"
-      - cmd: "{{ .ROOT_DIR }}/.bin/terraform workspace select -or-create=true -no-color '{{ .workspace }}'"
+      - cmd: "{{ .ROOT_DIR }}/.bin/terraform init -upgrade -no-color{{ .arguments }} |& tee '.terraform/init.log'"
+      - cmd: >-
+          {{ .ROOT_DIR }}/.bin/terraform workspace select -or-create=true -no-color '{{ .workspace }}' |& tee -a
+          '.terraform/init.log'
       - cmd: echo -e '\e[0;32mCompleted\e[0m'
-    status:
-      - test -f .terraform.lock.hcl
-      - test -d .terraform
 
   terraform:lock:
     aliases:
@@ -207,9 +217,11 @@ tasks:
     silent: true
     run: when_changed
     deps:
+      - task: terraform:workspace
       - task: terraform:init
     env:
       TF_IN_AUTOMATION: "true"
+      TF_INPUT: "false"
     cmds:
       - defer: "{{ if .EXIT_CODE }}echo -e '\e[1;31mFailed\e[0m'{{ end }}"
       - cmd: >-
@@ -238,22 +250,14 @@ tasks:
     vars:
       workspace:
         sh: cat .terraform/environment 2>/dev/null || echo -n "{{ .default }}"
-      options:
-        sh: |-
-          if [[ -f "variables/{{ .workspace }}.tfvars" ]]; then
-            FILE=$(realpath --relative-to="{{ .ROOT_DIR }}" "variables/{{ .workspace }}.tfvars")
-            echo "\n  \e[1;37m-var-file=${FILE}\e[0m"
-          fi
       arguments:
         sh: |-
           [[ -f 'variables/{{ .workspace }}.tfvars' ]] && echo -n ' -var-file=variables/{{ .workspace }}.tfvars' || true
     env:
       TF_IN_AUTOMATION: "true"
+      TF_INPUT: "false"
     cmds:
       - defer: "{{ if .EXIT_CODE }}echo -e '\e[1;31mFailed\e[0m'{{ end }}"
-      - cmd: "echo -e 'workspace: \e[1;37m{{ .workspace }}\e[0m'"
-      - if: '{{ ne .options "" }}'
-        cmd: "echo -e 'options: {{ .options }}\n'"
       - cmd: "{{ .ROOT_DIR }}/.bin/terraform get -update -no-color{{ .arguments }}"
       - cmd: echo -e '\e[0;32mPassed\e[0m'
 
@@ -274,22 +278,15 @@ tasks:
     vars:
       workspace:
         sh: cat .terraform/environment 2>/dev/null || echo -n "{{ .default }}"
-      options:
-        sh: |-
-          if [[ -f "variables/{{ .workspace }}.tfvars" ]]; then
-            FILE=$(realpath --relative-to="{{ .ROOT_DIR }}" "variables/{{ .workspace }}.tfvars" 2>&1)
-            echo "\n  \e[1;37m-var-file=${FILE}\e[0m"
-          fi
       arguments:
         sh: |-
           [[ -f 'variables/{{ .workspace }}.tfvars' ]] && echo -n ' -var-file=variables/{{ .workspace }}.tfvars' || true
     env:
       TF_IN_AUTOMATION: "true"
+      TF_INPUT: "false"
     cmds:
       - defer: "{{ if .EXIT_CODE }}echo -e '\e[1;31mFailed\e[0m'{{ end }}"
-      - cmd: "echo -e 'workspace: \e[1;37m{{ .workspace }}\e[0m'"
-      - if: '{{ ne .options "" }}'
-        cmd: "echo -e 'options: {{ .options }}\n'"
+      - defer: echo -n '{{ default "0" .EXIT_CODE }}' > '.terraform/validate'
       - cmd: "{{ .ROOT_DIR }}/.bin/terraform validate -no-color{{ .arguments }}"
       - cmd: echo -e '\e[0;32mPassed\e[0m'
 
@@ -309,28 +306,21 @@ tasks:
     silent: true
     deps:
       - task: terraform:validate
-      - task: terraform:lint
+      - task: tflint
     vars:
       workspace:
         sh: cat .terraform/environment 2>/dev/null || echo -n "{{ .default }}"
-      options:
-        sh: |-
-          if [[ -f "variables/{{ .workspace }}.tfvars" ]]; then
-            FILE=$(realpath --relative-to="{{ .ROOT_DIR }}" "variables/{{ .workspace }}.tfvars" 2>&1)
-            echo "\n  \e[1;37m-var-file=${FILE}\e[0m"
-          fi
       arguments:
         sh: |-
           [[ -f 'variables/{{ .workspace }}.tfvars' ]] && echo -n ' -var-file=variables/{{ .workspace }}.tfvars' || true
     env:
       TF_IN_AUTOMATION: "true"
+      TF_INPUT: "false"
     cmds:
       - defer: "{{ if .EXIT_CODE }}echo -e '\e[1;31mFailed\e[0m'{{ end }}"
-      - cmd: "echo -e 'workspace: \e[1;37m{{ .workspace }}\e[0m'"
-      - if: '{{ ne .options "" }}'
-        cmd: "echo -e 'options: {{ .options }}\n'"
+      - defer: echo -n '{{ default "0" .EXIT_CODE }}' > '.terraform/plan'
       - cmd: >-
-          {{ .ROOT_DIR }}/.bin/terraform plan -no-color -input=false{{ .arguments }} -out=terraform.tfplan |& tee
+          {{ .ROOT_DIR }}/.bin/terraform plan -no-color{{ .arguments }} -out=terraform.tfplan |& tee
           '.terraform/plan.log'
       - cmd: echo -e '\e[0;32mCompleted\e[0m'
     generates:
@@ -431,18 +421,17 @@ tasks:
     sources:
       - terraform.tfplan
     deps:
+      - task: terraform:workspace
       - task: terraform:plan
-    vars:
-      workspace:
-        sh: cat .terraform/environment 2>/dev/null || echo -n "{{ .default }}"
     env:
       TF_IN_AUTOMATION: "true"
+      TF_INPUT: "false"
     cmds:
       - defer: "{{ if .EXIT_CODE }}echo -e '\e[1;31mFailed\e[0m'{{ end }}"
+      - defer: echo -n '{{ default "0" .EXIT_CODE }}' > '.terraform/apply'
       # The terraform.tfplan file is rendered obsolete by even a partial apply of the configuration, so it must always
       # be deleted when an apply is run, otherwise the next run will fail with an error.
       - defer: rm -f terraform.tfplan
-      - cmd: "echo -e 'workspace: \e[1;37m{{ .workspace }}\e[0m'"
       - cmd: "{{ .ROOT_DIR }}/.bin/terraform apply -no-color terraform.tfplan |& tee '.terraform/apply.log'"
       - cmd: echo -e '\e[0;32mCompleted\e[0m'
 
@@ -458,6 +447,7 @@ tasks:
         sh: cat .terraform/environment 2>/dev/null || echo -n "{{ .default }}"
     env:
       TF_IN_AUTOMATION: "true"
+      TF_INPUT: "false"
     cmds:
       - defer: "{{ if .EXIT_CODE }}echo -e '\e[1;31mFailed\e[0m'{{ end }}"
       - cmd: "echo -e 'workspace: \e[1;37m{{ .workspace }}\e[0m'"
@@ -496,6 +486,5 @@ tasks:
       - defer: "{{ if .EXIT_CODE }}echo -e '\e[1;31mFailed\e[0m'{{ end }}"
       - cmd: rm -f terraform.tfplan
       - cmd: rm -f terraform.tfstate terraform.tfstate.backup
-      - cmd: rm -f .workspace
       - cmd: rm -rf .terraform
       - cmd: echo -e '\e[0;32mCompleted\e[0m'
